package hashname

import (
	"math/rand"
	"time"
	"unsafe"
)

var adjectives = []string{"shy", "able", "busy", "calm", "fair", "free", "good", "keen", "kind", "lazy", "mean", "neat", "nice", "rich", "rude", "sad", "tidy", "vain", "warm", "aloof", "bold", "bossy", "brave", "cruel", "dark", "eager", "frank", "funny", "fussy", "loyal", "merry", "moody", "naive", "nasty", "noisy", "poor", "prim", "proud", "quiet", "rigid", "silly", "tall", "tense", "timid", "tough", "ugly", "vague", "wild", "wise", "witty", "bitchy", "boring", "bright", "caring", "clever", "clumsy", "devout", "expert", "fancy", "gentle", "giving", "greedy", "grumpy", "happy", "harsh", "honest", "joyful", "light", "loving", "mature", "messy", "modest", "placid", "plain", "plucky", "polite", "short", "smart", "sneaky", "stable", "stingy", "strong", "stupid", "tender", "touchy", "tricky", "unique", "unkind", "untidy", "vulgar", "affable", "amiable", "amusing", "awkward", "callous", "careful", "cunning", "cynical", "dainty", "daring", "defiant", "dynamic", "finicky", "foolish", "grouchy", "helpful", "humble", "jealous", "leader", "lively", "miserly", "naughty", "nervous", "passive", "patient", "pompous", "pretty", "proper", "radical", "relaxed", "selfish", "simple", "sincere", "unhappy", "unlucky", "willing", "hopeful", "amicable", "annoying", "arrogant", "athletic", "boastful", "careless", "cautious", "charming", "clinging", "complex", "cowardly", "creative", "curious", "decisive", "detached", "diligent", "discreet", "dogmatic", "dreamer", "excited", "faithful", "fearless", "fighter", "forceful", "friendly", "generous", "gorgeous", "gracious", "gullible", "humorous", "impolite", "likeable", "lovable", "outgoing", "perverse", "pitiful", "pleasant", "popular", "powerful", "rational", "reliable", "reserved", "reverent", "romantic", "ruthless", "sensible", "serious", "sociable", "stubborn", "tactless", "tolerant", "trusting", "vengeful", "accepting", "adaptable", "agreeable", "ambitious", "cheerful", "confident", "convivial", "courteous", "deceitful", "dishonest", "easygoing", "efficient", "emotional", "energetic", "exuberant", "foolhardy", "forgiving", "handsome", "impartial", "impatient", "impulsive", "intuitive", "inventive", "obnoxious", "obsessive", "obstinate", "organized", "pleasing", "practical", "realistic", "religious", "resentful", "sarcastic", "secretive", "sensitive", "studious", "tireless", "truculent", "unselfish", "versatile", "aggressive", "articulate", "changeable", "compulsive", "conceited", "courageous", "demanding", "determined", "diplomatic", "frustrated", "gregarious", "indecisive", "indiscreet", "inflexible", "intolerant", "judgmental", "melancholy", "optimistic", "passionate", "patriotic", "personable", "pioneering", "possessive", "rebellious", "reflective", "thoughtful", "thrilling", "unassuming", "unreliable", "adventurous", "belligerent", "considerate", "disgruntled", "domineering", "embarrassed", "flirtatious"}
var names = []string{"smith", "johnson", "williams", "jones", "brown", "davis", "miller", "wilson", "moore", "taylor", "anderson", "thomas", "jackson", "white", "harris", "martin", "thompson", "garcia", "martinez", "robinson", "clark", "rodriguez", "lewis", "lee", "walker", "hall", "allen", "young", "hernandez", "king", "wright", "lopez", "hill", "scott", "green", "adams", "baker", "gonzalez", "nelson", "carter", "mitchell", "perez", "roberts", "turner", "phillips", "campbell", "parker", "evans", "edwards", "collins", "stewart", "sanchez", "morris", "rogers", "reed", "cook", "morgan", "bell", "murphy", "bailey", "rivera", "cooper", "richardson", "cox", "howard", "ward", "torres", "peterson", "gray", "ramirez", "james", "watson", "brooks", "kelly", "sanders", "price", "bennett", "wood", "barnes", "ross", "henderson", "coleman", "jenkins", "perry", "powell", "long", "patterson", "hughes", "flores", "washington", "butler", "simmons", "foster", "gonzales", "bryant", "alexander", "russell", "griffin", "diaz", "hayes", "myers", "ford", "hamilton", "graham", "sullivan", "wallace", "woods", "cole", "west", "jordan", "owens", "reynolds", "fisher", "ellis", "harrison", "gibson", "mcdonald", "cruz", "marshall", "ortiz", "gomez", "murray", "freeman", "wells", "webb", "simpson", "stevens", "tucker", "porter", "hunter", "hicks", "crawford", "henry", "boyd", "mason", "morales", "kennedy", "warren", "dixon", "ramos", "reyes", "burns", "gordon", "shaw", "holmes", "rice", "robertson", "hunt", "black", "daniels", "palmer", "mills", "nichols", "grant", "knight", "ferguson", "rose", "stone", "hawkins", "dunn", "perkins", "hudson", "spencer", "gardner", "stephens", "payne", "pierce", "berry", "matthews", "arnold", "wagner", "willis", "ray", "watkins", "olson", "carroll", "duncan", "snyder", "hart", "cunningham", "bradley", "lane", "andrews", "ruiz", "harper", "fox", "riley", "armstrong", "carpenter", "weaver", "greene", "lawrence", "elliott", "chavez", "sims", "austin", "peters", "kelley", "franklin", "lawson", "fields", "gutierrez", "ryan", "schmidt", "carr", "vasquez", "castillo", "wheeler", "chapman", "oliver", "montgomery", "richards", "williamson", "johnston", "banks", "meyer", "bishop", "mccoy", "howell", "alvarez", "morrison", "hansen", "fernandez", "garza", "harvey", "little", "burton", "stanley", "nguyen", "george", "jacobs", "reid", "kim", "fuller", "lynch", "dean", "gilbert", "garrett", "romero", "welch", "larson", "frazier", "burke", "hanson", "day", "mendoza", "moreno", "bowman", "medina", "fowler", "brewer", "hoffman", "carlson", "silva", "pearson", "holland"}
var verbs = []string{"accept", "admire", "afford", "allow", "appear", "apply", "arrange", "attack", "avoid", "bake", "baste", "beat", "binge", "bite", "blanch", "blend", "boil", "break", "brown", "build", "burn", "bury", "buy", "carry", "carve", "catch", "check", "chew", "chill", "choose", "chop", "churn", "clean", "close", "collect", "consume", "control", "cook", "cool", "copy", "core", "correct", "cost", "count", "cover", "create", "crumple", "cut", "decorate", "deliver", "demand", "deny", "describe", "destroy", "dice", "digest", "dine", "discard", "discover", "discuss", "divide", "drape", "draw", "dress", "drink", "drop", "dry", "eat", "enjoy", "enrich", "examine", "expect", "explain", "express", "farm", "feast", "feed", "feel", "fill", "film", "find", "finish", "fix", "fold", "follow", "force", "forget", "form", "found", "fry", "garnish", "get", "give", "glaze", "gobble", "grind", "grow", "guzzle", "handle", "have", "hide", "hit", "hold", "hope", "imagine", "improve", "infuse", "ingest", "insert", "keep", "kick", "knock", "know", "lay", "learn", "leave", "lend", "lick", "lift", "like", "limit", "link", "look", "lose", "love", "make", "mark", "mash", "measure", "melt", "mention", "mill", "mince", "miss", "mix", "moisten", "mound", "move", "munch", "need", "nibble", "notice", "obtain", "offer", "open", "order", "own", "pack", "paint", "pass", "pay", "peel", "pick", "pierce", "place", "pour", "prefer", "preheat", "prepare", "present", "press", "prick", "produce", "provide", "pull", "puree", "push", "quarter", "raise", "receive", "recognize", "record", "reduce", "refresh", "refuse", "reheat", "remember", "remove", "repeat", "replace", "report", "represent", "require", "return", "reveal", "ring", "roast", "roll", "salt", "saute", "save", "say", "scatter", "scoop", "scrape", "scrub", "season", "see", "sell", "send", "separate", "serve", "set", "settle", "shake", "share", "shave", "show", "shred", "sift", "simmer", "skim", "skin", "slice", "slide", "slip", "slit", "smear", "soak", "sort", "spoon", "spread", "sprinkle", "stir", "strain", "strew", "study", "stuff", "surround", "swallow", "take", "taste", "tenderize", "test", "thaw", "thin", "throw", "tie", "tilt", "tip", "top", "toss", "touch", "trim", "try", "turn", "twist", "use", "want", "warm", "watch", "whip", "wilt", "win", "wolf", "wrap"}
var foods = []string{"acai", "alfalfa", "alfredo", "angus", "apple", "artichoke", "arugula", "asiago", "asparagus", "asti", "babka", "bacardi", "bagel", "baguette", "bailey", "banana", "bao", "basil", "bean", "beck", "bellini", "benedict", "biscotti", "biscuit", "blackberry", "bleu", "blintz", "blueberry", "bostock", "brandy", "breadstick", "brie", "brownie", "bud", "burger", "butter", "buttercream", "buttercup", "butternut", "butters", "butterscotch", "caesar", "cake", "candy", "cantaloupe", "caramel", "carrot", "cashew", "cauliflower", "cayenne", "celery", "chai", "challah", "cheddar", "cheerio", "cheesecake", "cherry", "chestnut", "chex", "chickpea", "chiffon", "chili", "chip", "chipotle", "chive", "churro", "cinnamon", "clementine", "cloudberry", "clove", "cobbler", "coconut", "colby", "colt", "concha", "cookie", "coriander", "cranberry", "croissant", "crumble", "crumpet", "cucumber", "cupcake", "curry", "custard", "daikon", "delmonico", "dewberry", "donut", "dumpling", "eclair", "eggplant", "empanada", "endive", "espresso", "falafel", "fig", "flan", "flapjack", "focaccia", "fondue", "frank", "fritatta", "frito", "fritter", "fudge", "garlic", "ginger", "gnocchi", "goji", "gouda", "grapefruit", "guacamole", "ham", "hambone", "hazelnut", "herb", "holly", "honey", "jack", "jalapeno", "jameson", "jelly", "jellybean", "kale", "kiwi", "kobe", "kumquat", "latte", "lavender", "lemon", "lime", "linguini", "macaroni", "macaroon", "mango", "margarita", "marshmallow", "martini", "meatball", "meatloaf", "melon", "meringue", "meunster", "milkshake", "mochi", "mooncake", "mousse", "moxie", "muffin", "mulberry", "mushroom", "nacho", "napa", "napoleon", "nectarine", "noodle", "nori", "nugget", "nutella", "nutmeg", "oatmeal", "okra", "olive", "onion", "oolong", "oregano", "pancake", "papaya", "parsnip", "pastry", "peacan", "peach", "peanut", "peapod", "pecorino", "pepper", "pepperoni", "pesto", "pickle", "pie", "pierogi", "pineapple", "pinot", "pirogi", "pistachio", "pizza", "plantain", "plum", "poppy", "porky", "porter", "potato", "praline", "pudding", "pumpkin", "queso", "quiche", "quinoa", "radish", "raisin", "ramen", "raspberry", "ratatouille", "red", "reeses", "reisling", "reuben", "rhubarb", "rose", "rosemary", "roux", "rugelach", "saffron", "sage", "sake", "salami", "salmonberry", "schnitzel", "scone", "scotch", "shallot", "sherry", "shortbread", "snickers", "soda", "sourdough", "soybean", "spaghetti", "sponge", "sprite", "sprout", "squash", "stoli", "strawberry", "sushi", "taco", "taffy", "tangerine", "tayberry", "toast", "toffee", "tofu", "tomato", "truffle", "turnip", "waffles", "walnut", "wasabi", "watercress", "watermelon", "wonton", "yam", "zima", "zin", "zucchini"}

//GetNameFromHash returns a 4-part phrase from a 32-bit hash
func GetNameFromHash(hash uint32) string {
	a := (*[4]byte)(unsafe.Pointer(&hash))
	return adjectives[a[0]] + "-" + names[a[1]] + "-" + verbs[a[2]] + "-" + foods[a[3]]
}

//GetNameFromShortHash returns a 2-part phrase for 2 16-bit hash
func GetNameFromShortHash(hash uint16) string {
	a := (*[2]byte)(unsafe.Pointer(&hash))
	return adjectives[a[0]] + "-" + names[a[1]]
}

//GetRandomName returns a random 2-part phrase
func GetRandomName() string {
	rand.Seed(time.Now().UTC().UnixNano())
	return adjectives[rand.Intn(256)] + "-" + names[rand.Intn(256)]
}
